In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import sys
sys.path.append("..")

In [3]:
survey_df = pd.read_csv('../data/laurelhurst_survey_with_address.csv')
survey_df

passcode    mode  1_cook  1_wash  1_health  1_warm  1_cool  1_safe  \
0       36597  online     2.0     3.0       1.0     4.0     1.0     4.0   
1       37097  online     4.0     2.0       4.0     4.0     2.0     2.0   
2       36807  online     3.0     4.0       5.0     4.0     2.0     4.0   
3       36119  online     4.0     2.0       2.0     5.0     1.0     3.0   
4       36971  online     5.0     3.0       3.0     5.0     1.0     3.0   
..        ...     ...     ...     ...       ...     ...     ...     ...   
257     36435   paper     4.0     5.0       3.0     4.0     3.0     2.0   
258     35801   paper     1.0     3.0       3.0     4.0     1.0     3.0   
259     36737   paper     3.0     4.0       3.0     5.0     2.0     4.0   
260     36483   paper     3.0     3.0       4.0     4.0     2.0     4.0   
261     36689   paper     4.0     3.0       2.0     4.0     2.0     3.0   

     1_comm  1_transp  ...      ID  CLUSTER           PIN  \
0       2.0       1.0  ...  1279.0     74.0  4.221900e+09   
1       3.0       3.0  ...  1772.0     95.0  1.525049e+09   
2       4.0       4.0  ...   904.0     54.0  7.613701e+09   
3       3.0       1.0  ...   824.0     49.0  4.218401e+09   
4       3.0       4.0  ...   268.0     17.0  7.230002e+08   
..      ...       ...  ...     ...      ...           ...   
257     3.0       3.0  ...   428.0     25.0  4.217401e+09   
258     4.0       5.0  ...   331.0     19.0  7.230004e+08   
259     4.0       NaN  ...   185.0     12.0  4.217401e+09   
260     5.0       4.0  ...    71.0      4.0  4.217402e+09   
261     2.0       3.0  ...  1704.0     93.0  4.217401e+09   

                                  TAXPAYER NAME                  ADDRESS  \
0                   YOUNG-SPARLING FAMILY TRUST        5127 47TH AVE NE    
1    VILLAGE MANOR LLC 42 UNITS                  3925 NE 45TH ST APT 111   
2             BRUNNER HELEN J+CIMA,                     4845 NE 41ST ST    
3             CHARTIER CRAIG A+JAMIE L CN              4507 51ST AVE NE    
4             WEIS ERIK                                3803 40TH AVE NE    
..                                          ...                      ...   
257           TUTMARC MICHAEL                           3857 45TH AVE NE   
258           DI JULIO ROBERT L                        3812 41ST AVE NE    
259           BURGSTAHLER DAVID C+SHERYL               3608 43RD AVE NE    
260           HERBER PAUL F+ALISON G HERB               4229 NE 33RD ST    
261           TOLMACHEVA MARINA                         4107 NE 45TH ST    

        CITY      ZIP   latitude   longitude  area  
0    SEATTLE  98105.0  47.666871 -122.277676     A  
1    SEATTLE  98105.0  47.660871 -122.285510     C  
2    SEATTLE  98105.0  47.658138 -122.274650     F  
3    SEATTLE  98105.0  47.661594 -122.272780     E  
4    SEATTLE  98105.0  47.656788 -122.285200     D  
..       ...      ...        ...         ...   ...  
257  SEATTLE  98105.0  47.656447 -122.279671     D  
258  SEATTLE  98105.0  47.657044 -122.283639     D  
259  SEATTLE  98105.0  47.654683 -122.280300     G  
260  SEATTLE  98105.0  47.651876 -122.279714     G  
261  SEATTLE  98105.0  47.661136 -122.283106     D  

[262 rows x 163 columns]

In [4]:
# Select the columns
columns = ['7_water', '7_food', '7_meds', '7_transp', '7_comm', '7_faid', '7_warm', '7_sani', '7_power', '7_shelter']
corr_matrix = survey_df[columns].corr()
corr_matrix

7_water    7_food    7_meds  7_transp    7_comm    7_faid  \
7_water    1.000000  0.728706  0.406466  0.354223  0.315896  0.343367   
7_food     0.728706  1.000000  0.475937  0.394563  0.410704  0.476933   
7_meds     0.406466  0.475937  1.000000  0.459641  0.405880  0.473611   
7_transp   0.354223  0.394563  0.459641  1.000000  0.633406  0.454050   
7_comm     0.315896  0.410704  0.405880  0.633406  1.000000  0.701214   
7_faid     0.343367  0.476933  0.473611  0.454050  0.701214  1.000000   
7_warm     0.416483  0.497655  0.361538  0.504972  0.599603  0.655960   
7_sani     0.446475  0.412000  0.302218  0.552207  0.500953  0.429666   
7_power    0.546579  0.535161  0.513374  0.578255  0.569080  0.481384   
7_shelter  0.528248  0.533765  0.466690  0.527163  0.457175  0.434611   

             7_warm    7_sani   7_power  7_shelter  
7_water    0.416483  0.446475  0.546579   0.528248  
7_food     0.497655  0.412000  0.535161   0.533765  
7_meds     0.361538  0.302218  0.513374   0.466690  
7_transp   0.504972  0.552207  0.578255   0.527163  
7_comm     0.599603  0.500953  0.569080   0.457175  
7_faid     0.655960  0.429666  0.481384   0.434611  
7_warm     1.000000  0.470886  0.583098   0.516450  
7_sani     0.470886  1.000000  0.541089   0.556526  
7_power    0.583098  0.541089  1.000000   0.706062  
7_shelter  0.516450  0.556526  0.706062   1.000000

In [5]:
# get the PMF of each column of the data
sharing_pref_pmf = survey_df[columns].apply(pd.value_counts, normalize=True)
sharing_pref_pmf

7_water    7_food    7_meds  7_transp    7_comm    7_faid    7_warm  \
0.0  0.027237  0.015686  0.152610  0.023715  0.011952  0.003906  0.003937   
1.0  0.389105  0.333333  0.281124  0.189723  0.151394  0.128906  0.165354   
2.0  0.307393  0.372549  0.248996  0.434783  0.322709  0.246094  0.311024   
3.0  0.276265  0.278431  0.317269  0.351779  0.513944  0.621094  0.519685   

       7_sani   7_power  7_shelter  
0.0  0.043478  0.027668   0.019685  
1.0  0.272727  0.328063   0.311024  
2.0  0.351779  0.379447   0.409449  
3.0  0.332016  0.264822   0.259843

In [6]:
# find the covariance matrix of the generated RVs
cov_mat = survey_df[columns].cov()
cov_mat

7_water    7_food    7_meds  7_transp    7_comm    7_faid  \
7_water    0.749240  0.517230  0.373478  0.242236  0.212892  0.217034   
7_food     0.517230  0.669693  0.412955  0.254996  0.261687  0.285130   
7_meds     0.373478  0.412955  1.141016  0.389174  0.334694  0.371115   
7_transp   0.242236  0.254996  0.389174  0.625698  0.390329  0.260861   
7_comm     0.212892  0.261687  0.334694  0.390329  0.600861  0.398805   
7_faid     0.217034  0.285130  0.371115  0.260861  0.398805  0.533088   
7_warm     0.274906  0.310520  0.294176  0.304717  0.356183  0.363792   
7_sani     0.340517  0.297610  0.284125  0.386231  0.345403  0.278126   
7_power    0.392465  0.363076  0.453589  0.379299  0.364960  0.289066   
7_shelter  0.368367  0.350930  0.399452  0.333333  0.284707  0.253451   

             7_warm    7_sani   7_power  7_shelter  
7_water    0.274906  0.340517  0.392465   0.368367  
7_food     0.310520  0.297610  0.363076   0.350930  
7_meds     0.294176  0.284125  0.453589   0.399452  
7_transp   0.304717  0.386231  0.379299   0.333333  
7_comm     0.356183  0.345403  0.364960   0.284707  
7_faid     0.363792  0.278126  0.289066   0.253451  
7_warm     0.583051  0.318683  0.367745   0.315203  
7_sani     0.318683  0.780977  0.398233   0.395277  
7_power    0.367745  0.398233  0.692233   0.471133  
7_shelter  0.315203  0.395277  0.471133   0.643942

In [7]:
# Cholesky decomposition
L = np.linalg.cholesky(cov_mat)
L

array([[ 0.86558652,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.59754881,  0.55913163,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.43147366,  0.27744611,  0.93694707,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.27985189,  0.15697708,  0.24000583,  0.68200901,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.24595165,  0.20517286,  0.18319905,  0.3597061 ,  0.57907001,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.25073671,  0.24198632,  0.20896615,  0.15036865,  0.3369467 ,
         0.4815094 ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.31759489,  0.21594446,  0.1037726 ,  0.23025098,  0.22783108,
         0.20524886,  0.52700451,  0.        

In [8]:
# Check Cholesky decomposition
L @ L.T

array([[0.74924003, 0.5172302 , 0.37347778, 0.24223602, 0.21289243,
        0.21703431, 0.27490585, 0.34051697, 0.39246502, 0.368367  ],
       [0.5172302 , 0.66969276, 0.41295547, 0.25499602, 0.26168675,
        0.28512963, 0.31051983, 0.29760956, 0.3630757 , 0.35092961],
       [0.37347778, 0.41295547, 1.14101568, 0.38917415, 0.33469388,
        0.37111467, 0.29417621, 0.28412495, 0.45358941, 0.39945246],
       [0.24223602, 0.25499602, 0.38917415, 0.62569797, 0.39032911,
        0.26086132, 0.30471713, 0.38623108, 0.3792988 , 0.33333333],
       [0.21289243, 0.26168675, 0.33469388, 0.39032911, 0.60086056,
        0.39880478, 0.3561828 , 0.3454029 , 0.36496017, 0.2847068 ],
       [0.21703431, 0.28512963, 0.37111467, 0.26086132, 0.39880478,
        0.53308824, 0.36379198, 0.27812559, 0.28906596, 0.25345066],
       [0.27490585, 0.31051983, 0.29417621, 0.30471713, 0.3561828 ,
        0.36379198, 0.58305064, 0.31868273, 0.36774502, 0.31520319],
       [0.34051697, 0.29760956, 0.2841249

In [19]:
# Generate uncorrelated random variables
uncorr_sharing_preferences = np.zeros((10, 1000))
np.random.seed(0)
for i,rsc in enumerate(columns):
    for j in range(uncorr_sharing_preferences.shape[1]):
        uncorr_sharing_preferences[i, j] = np.random.choice(sharing_pref_pmf.index, p=sharing_pref_pmf[rsc].values)
uncorr_sharing_preferences

array([[2., 2., 2., ..., 3., 1., 2.],
       [2., 0., 2., ..., 2., 2., 2.],
       [3., 2., 2., ..., 1., 3., 3.],
       ...,
       [2., 2., 3., ..., 3., 2., 3.],
       [2., 2., 2., ..., 1., 3., 3.],
       [2., 3., 3., ..., 3., 1., 3.]])

In [10]:
print(np.corrcoef(uncorr_sharing_preferences).round(2))

[[ 1.    0.01 -0.01 -0.01  0.   -0.02  0.01  0.    0.03  0.04]
 [ 0.01  1.    0.02  0.01 -0.01  0.02  0.02  0.02  0.01  0.01]
 [-0.01  0.02  1.    0.03 -0.03  0.01 -0.03  0.01  0.05 -0.04]
 [-0.01  0.01  0.03  1.   -0.01 -0.01 -0.03 -0.01  0.01  0.03]
 [ 0.   -0.01 -0.03 -0.01  1.    0.04 -0.01 -0.01  0.02 -0.02]
 [-0.02  0.02  0.01 -0.01  0.04  1.   -0.03 -0.   -0.02 -0.  ]
 [ 0.01  0.02 -0.03 -0.03 -0.01 -0.03  1.    0.   -0.02 -0.02]
 [ 0.    0.02  0.01 -0.01 -0.01 -0.    0.    1.   -0.01  0.01]
 [ 0.03  0.01  0.05  0.01  0.02 -0.02 -0.02 -0.01  1.   -0.04]
 [ 0.04  0.01 -0.04  0.03 -0.02 -0.   -0.02  0.01 -0.04  1.  ]]


In [11]:
print(np.cov(uncorr_sharing_preferences).round(2))

[[ 0.75  0.01 -0.01 -0.01  0.   -0.02  0.01  0.    0.02  0.03]
 [ 0.01  0.7   0.02  0.01 -0.    0.01  0.01  0.02  0.01  0.  ]
 [-0.01  0.02  1.12  0.03 -0.03  0.01 -0.02  0.01  0.04 -0.04]
 [-0.01  0.01  0.03  0.62 -0.01 -0.01 -0.02 -0.    0.01  0.02]
 [ 0.   -0.   -0.03 -0.01  0.6   0.02 -0.01 -0.    0.01 -0.01]
 [-0.02  0.01  0.01 -0.01  0.02  0.57 -0.02 -0.   -0.02 -0.  ]
 [ 0.01  0.01 -0.02 -0.02 -0.01 -0.02  0.59  0.   -0.01 -0.01]
 [ 0.    0.02  0.01 -0.   -0.   -0.    0.    0.81 -0.    0.01]
 [ 0.02  0.01  0.04  0.01  0.01 -0.02 -0.01 -0.    0.67 -0.02]
 [ 0.03  0.   -0.04  0.02 -0.01 -0.   -0.01  0.01 -0.02  0.68]]


In [18]:
# Generate correlated random variables
corr_sharing_pref = L @ uncorr_sharing_preferences
corr_sharing_pref

array([[1.73117305, 1.73117305, 1.73117305, ..., 2.59675957, 0.86558652,
        1.73117305],
       [2.31336088, 1.19509763, 2.31336088, ..., 2.91090969, 1.71581207,
        2.31336088],
       [4.22868075, 2.73684146, 3.29173368, ..., 2.78626026, 3.79720709,
        4.22868075],
       ...,
       [3.87449867, 3.70738656, 4.65807245, ..., 5.24298359, 3.95952301,
        4.75775431],
       [4.26603626, 3.86073367, 4.37314527, ..., 4.20599315, 4.74358096,
        5.18987937],
       [4.32770958, 4.38470979, 5.04204396, ..., 5.19430583, 3.94656625,
        5.38214967]])

In [14]:
print(np.corrcoef(corr_sharing_pref).round(2))

[[1.   0.75 0.33 0.35 0.34 0.35 0.46 0.44 0.56 0.56]
 [0.75 1.   0.4  0.41 0.44 0.5  0.55 0.42 0.56 0.57]
 [0.33 0.4  1.   0.54 0.45 0.53 0.38 0.3  0.57 0.49]
 [0.35 0.41 0.54 1.   0.66 0.5  0.52 0.52 0.61 0.56]
 [0.34 0.44 0.45 0.66 1.   0.74 0.63 0.49 0.6  0.49]
 [0.35 0.5  0.53 0.5  0.74 1.   0.66 0.42 0.52 0.46]
 [0.46 0.55 0.38 0.52 0.63 0.66 1.   0.46 0.59 0.53]
 [0.44 0.42 0.3  0.52 0.49 0.42 0.46 1.   0.54 0.58]
 [0.56 0.56 0.57 0.61 0.6  0.52 0.59 0.54 1.   0.72]
 [0.56 0.57 0.49 0.56 0.49 0.46 0.53 0.58 0.72 1.  ]]


In [15]:
corr_matrix.round(2)

7_water  7_food  7_meds  7_transp  7_comm  7_faid  7_warm  7_sani  \
7_water       1.00    0.73    0.41      0.35    0.32    0.34    0.42    0.45   
7_food        0.73    1.00    0.48      0.39    0.41    0.48    0.50    0.41   
7_meds        0.41    0.48    1.00      0.46    0.41    0.47    0.36    0.30   
7_transp      0.35    0.39    0.46      1.00    0.63    0.45    0.50    0.55   
7_comm        0.32    0.41    0.41      0.63    1.00    0.70    0.60    0.50   
7_faid        0.34    0.48    0.47      0.45    0.70    1.00    0.66    0.43   
7_warm        0.42    0.50    0.36      0.50    0.60    0.66    1.00    0.47   
7_sani        0.45    0.41    0.30      0.55    0.50    0.43    0.47    1.00   
7_power       0.55    0.54    0.51      0.58    0.57    0.48    0.58    0.54   
7_shelter     0.53    0.53    0.47      0.53    0.46    0.43    0.52    0.56   

           7_power  7_shelter  
7_water       0.55       0.53  
7_food        0.54       0.53  
7_meds        0.51       0.47  
7_transp      0.58       0.53  
7_comm        0.57       0.46  
7_faid        0.48       0.43  
7_warm        0.58       0.52  
7_sani        0.54       0.56  
7_power       1.00       0.71  
7_shelter     0.71       1.00

In [16]:
print(np.cov(corr_sharing_pref).round(2))

[[0.56 0.39 0.27 0.17 0.16 0.16 0.21 0.25 0.3  0.29]
 [0.39 0.49 0.31 0.19 0.19 0.21 0.23 0.23 0.28 0.28]
 [0.27 0.31 1.18 0.39 0.31 0.35 0.25 0.25 0.44 0.36]
 [0.17 0.19 0.39 0.43 0.27 0.2  0.21 0.26 0.29 0.26]
 [0.16 0.19 0.31 0.27 0.39 0.28 0.24 0.23 0.27 0.21]
 [0.16 0.21 0.35 0.2  0.28 0.36 0.24 0.19 0.22 0.19]
 [0.21 0.23 0.25 0.21 0.24 0.24 0.36 0.21 0.26 0.22]
 [0.25 0.23 0.25 0.26 0.23 0.19 0.21 0.59 0.3  0.31]
 [0.3  0.28 0.44 0.29 0.27 0.22 0.26 0.3  0.52 0.36]
 [0.29 0.28 0.36 0.26 0.21 0.19 0.22 0.31 0.36 0.47]]


In [17]:
cov_mat.round(2)

7_water  7_food  7_meds  7_transp  7_comm  7_faid  7_warm  7_sani  \
7_water       0.75    0.52    0.37      0.24    0.21    0.22    0.27    0.34   
7_food        0.52    0.67    0.41      0.25    0.26    0.29    0.31    0.30   
7_meds        0.37    0.41    1.14      0.39    0.33    0.37    0.29    0.28   
7_transp      0.24    0.25    0.39      0.63    0.39    0.26    0.30    0.39   
7_comm        0.21    0.26    0.33      0.39    0.60    0.40    0.36    0.35   
7_faid        0.22    0.29    0.37      0.26    0.40    0.53    0.36    0.28   
7_warm        0.27    0.31    0.29      0.30    0.36    0.36    0.58    0.32   
7_sani        0.34    0.30    0.28      0.39    0.35    0.28    0.32    0.78   
7_power       0.39    0.36    0.45      0.38    0.36    0.29    0.37    0.40   
7_shelter     0.37    0.35    0.40      0.33    0.28    0.25    0.32    0.40   

           7_power  7_shelter  
7_water       0.39       0.37  
7_food        0.36       0.35  
7_meds        0.45       0.40  
7_transp      0.38       0.33  
7_comm        0.36       0.28  
7_faid        0.29       0.25  
7_warm        0.37       0.32  
7_sani        0.40       0.40  
7_power       0.69       0.47  
7_shelter     0.47       0.64